stages:
    - deploy

variables:
    SSL_DIR: ./ssl
    SSL_KEYFILE: $SSL_DIR/key.pem
    SSL_CERTFILE: $SSL_DIR/cert.pem

deploy:
    stage: deploy
    only:
      - main
    script:
        - mkdir $SSL_DIR

        - touch "$SSL_CERTFILE"
        - printf "%s" "$SSL_CERT" > "$SSL_CERTFILE"

        - touch "$SSL_KEYFILE"
        - printf "%s" "$SSL_KEY" > "$SSL_KEYFILE"

        - sudo docker stop message-router && sudo docker rm message-router

        - sudo docker buildx build -t message-router .
        - sudo docker run -d --restart=unless-stopped --network nginx_bridge --ip 172.23.0.69 -p "1488:8080" --name message-router message-router
